language: android
sudo: false
jdk: oraclejdk8
dist: trusty
group: stable

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-27

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
    - $HOME/.android/build-cache

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace